export { useDict } from './useDict'
export { useMessage } from './useMessage'
export { usePermissions } from './usePermissions'
export { useSetting } from './useSetting'
export { useTable } from './useTable'
